version: '2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
    - 80:80
    - 443:443
    volumes:
    - ~/.easypage/certs:/etc/nginx/certs:rw
    - /etc/nginx/vhost.d
    - /usr/share/nginx/html
    - /var/run/docker.sock:/tmp/docker.sock:ro

  letsencrypt-agent:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
    - nginx-proxy
    environment:
    - LETSENCRYPT_TEST=true

networks:
  default:
    external:
      name: frontend-network
